# GitHub Actions Workflow para MLOps - Projeto Churn Model
# Autor: Dr. Eddy Giusepe Chirinos Isidro
# Descrição: Pipeline automático para treinar modelo de churn e gerar métricas

name: 🤖 ML Workflow - Pipeline Churn Model Training

# 📅 QUANDO EXECUTAR (Triggers):
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: iterative/setup-cml@v2
      - name: Install Packages
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Format
        run: black *.py
      - name: Train
        run: python train.py
      - name: Evaluation
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
            
          echo '## Confusion Matrix Plot' >> report.md
          echo '![Confusion Matrix](model_results.png)' >> report.md

          echo '## ROC Curve' >> report.md
          echo '![ROC Curve](roc_curve.png)' >> report.md

          cml comment create report.md
